#!/usr/bin/env bash

function log() {
	builtin echo $@
}

function log() {
	return
}

function update() {
	pushd "$1" > /dev/null
	log Updating...

	if [ master != "$(git rev-parse --abbrev-ref HEAD)" ]; then
		log - HEAD is not "master"
	fi
#	git stash
#	git pull origin master 1> /dev/null 2>&1
#	git status -sb
	popd > /dev/null
}

function locate() {
	local SOURCE="$1"
	local TARGET

	while [ -h "$SOURCE" ]; do
		TARGET="$(readlink "$SOURCE")"
		if [[ $SOURCE == /* ]]; then
			SOURCE="$TARGET"
		else
		    SOURCE="$(dirname "$SOURCE")/$TARGET"
	    fi
	done

	echo $SOURCE
}

function install() {
	log Installing...
	if [ -d "$1/install.d" ]; then
		for FILE in $1/install.d/*.sh; do
			if [ -r "$FILE" ]; then
				log - Module $(basename "$FILE")
				if [ -h "$FILE" ]; then
					FILE=$(locate "$FILE")
				fi
				. "$FILE" "$(cd "$(dirname "$FILE")" && pwd)" $2
			fi
		done
	fi
}

FROM=$(dirname "$BASH_SOURCE")
TO=~/

update "$FROM"
install "$FROM" "$TO"
