#!/bin/bash
if which is_xdebug_off > /dev/null && ! is_xdebug_off; then
    exit 1
fi

HOST="localhost"
PORT=8000
DOCROOT="web"
CONSOLE="app/console"

cd "$(dirname "$0")"
if [ -f "server.conf" ]; then
    . server.conf
fi
cd ..

SERVER="$HOST:$PORT"
OPTION="${1-start}"
case "$OPTION" in
    stop)
        $CONSOLE server:stop $SERVER
        ;;

    restart)
        $CONSOLE server:stop $SERVER
        while lsof -ti:"$PORT" > /dev/null; do echo -n; done
        OPTION="start"
        ;&

    start|run)
        $CONSOLE server:${OPTION} $SERVER --docroot="$DOCROOT"
        ;;
esac

