#!/usr/bin/env bash
 
PREVIOUS_HEAD=$1
NEW_HEAD=$2
BRANCH_SWITCH=$3
 
# Show branch description if one's defined
if [ $BRANCH_SWITCH == "1" -a $PREVIOUS_HEAD != $NEW_HEAD ]; then
  DESCRIPTION=$(git config --get branch.$(git rev-parse --abbrev-ref HEAD).description 2> /dev/null)
  if [ "$DESCRIPTION" ]; then
    echo "Description: $DESCRIPTION"
  fi
fi
